// Using constants instead of strings used directly prevents errors due to typos etc


export const CLEAR_GATEWAYS = 'CLEAR_GATEWAYS';
export const TOGGLE_GATEWAY_DELETE = 'TOGGLE_GATEWAY_DELETE';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const GET_GATEWAYS_SUCCESS = 'GET_GATEWAYS_SUCCESS';
export const GET_GATEWAYS_FAILED = 'GET_GATEWAYS_FAILED';
export const GET_GATEWAYS_REQUESTED = 'GET_GATEWAYS_REQUESTED';

export const GET_GATEWAY_SUCCESS = 'GET_GATEWAY_SUCCESS';
export const GET_GATEWAY_FAILED = 'GET_GATEWAY_FAILED';
export const GET_GATEWAY_REQUESTED = 'GET_GATEWAY_REQUESTED';

export const UPSERT_GATEWAY_SUCCESS = 'UPSERT_GATEWAY_SUCCESS';
export const UPSERT_GATEWAY_FAILED = 'UPSERT_GATEWAY_FAILED';
export const UPSERT_GATEWAY_REQUESTED = 'UPSERT_GATEWAY_REQUESTED';

export const REMOVE_GATEWAY_SUCCESS = 'REMOVE_GATEWAY_SUCCESS';
export const REMOVE_GATEWAY_FAILED = 'REMOVE_GATEWAY_FAILED';
export const REMOVE_GATEWAY_REQUESTED = 'REMOVE_GATEWAY_REQUESTED';